### ISSUE TITLE
HandlerTest

### ISSUE THREAD

**Issue by MarshalT** [nnhy/NewLife.Net.Tests#4]
demo里newLife.core是7.3.6870.42457 从8.1开始客户端收到的数据数据包的顺序错乱了

如下：
请选择运行模式：1，服务端；2，客户端  1
20:05:36.912  1 N - Net 准备开始监听4个服务器
20:05:36.929  1 N - NetTcp.Start Tcp://0.0.0.0:520
20:05:36.935  1 N - Net 开始监听 Tcp://0.0.0.0:520
20:05:36.937  1 N - Net 开始监听 Tcp://:::520
20:05:36.957  1 N - Net 开始监听 Udp://0.0.0.0:520
20:05:36.960  1 N - Net 开始监听 Udp://:::520
20:05:36.961  1 N - Net 准备就绪！
OK!
20:05:37.085  6 Y T 处理：0/0/0tps
20:05:39.387  4 Y - Tcp.New 127.0.0.1:50536
20:05:39.463  4 Y - Tcp.Recv [11]: 01010700E4BDA0E5A5BD31
20:05:39.483  4 Y - Tcp.收到：你好1
20:05:39.501  4 Y - Tcp.Send [11]: 01010700E4BDA0E5A5BD31
20:05:39.506 10 Y - Tcp.Recv [44]: 01020700E4BDA0E5A5BD3201030700E4BDA0E5A5BD3301040700E4BDA0E5A5BD
20:05:39.507 10 Y - Tcp.收到：你好2
20:05:39.508 10 Y - Tcp.Send [11]: 01020700E4BDA0E5A5BD32
20:05:39.509 10 Y - Tcp.收到：你好3
20:05:39.510 10 Y - Tcp.Send [11]: 01030700E4BDA0E5A5BD33
20:05:39.512 10 Y - Tcp.收到：你好4
20:05:39.512 10 Y - Tcp.Send [11]: 01040700E4BDA0E5A5BD34
20:05:39.513 10 Y - Tcp.收到：你好5
20:05:39.514 10 Y - Tcp.Send [11]: 01050700E4BDA0E5A5BD35
20:05:40.105  9 Y T 处理：0/0/0tps 在线：1/1 发送：5/0/0tps

请选择运行模式：1，服务端；2，客户端  2
20:05:39.346  1 N - Tcp.Open Tcp://0.0.0.0:50536=>127.0.0.1:520
OK!
20:05:39.524  6 Y T 发送：5/0/0tps
20:05:39.527  9 Y - Tcp.Recv [11]: 01010700E4BDA0E5A5BD31
20:05:39.587 11 Y - 收到：你好2
20:05:39.593  4 Y - Tcp.Recv [44]: 01020700E4BDA0E5A5BD3201030700E4BDA0E5A5BD3301040700E4BDA0E5A5BD
20:05:39.595 11 Y - 收到：你好4
20:05:39.595  7 Y - 收到：你好2
20:05:39.595  6 Y - 收到：你好3
20:05:39.650 13 Y - 收到：你好5

**Comment by xxred** [comment]
@MarshalT 这个相关的例程已合并至NewLife.Net项目，麻烦移步[NewLife.Net](https://github.com/NewLifeX/NewLife.Net)

**Comment by MarshalT** [comment]
@xxred  NewLife.Net里我运行也是一样的效果 第二包数据有两次并且数据包的顺序是乱的。

![image](https://user-images.githubusercontent.com/33778588/54925374-25fc2800-4f49-11e9-8807-e491fff5d772.png)

**Comment by nnhy** [comment]
今晚检查解决问题

**Comment by MarshalT** [comment]
@nnhy  从8.1版开始出现的这个问题。

**Comment by nnhy** [comment]
最近一个月，核心网络库进行了性能优化，对已拆包完成的消息进行异步处理，以提升吞吐率。
在判断消息重叠时仅判断IMessage类型而未判断Packet类型，导致原始数据包在未经拷贝的情况下送入异步处理程序，从而出现了不可预测的数据错乱，表现为乱序，实则是多个线程共用了数据区。
该BUG在最新0327的发布中已修正！

只有完成了数据包拷贝的消息，才走异步处理，避免用户消息中引用了IOCP层数据包；

https://github.com/NewLifeX/NewLife.Net/commit/59c9fc48021e89a7e7a83f680e06307197e03483

**Comment by MarshalT** [comment]
好的，多谢。
