### ISSUE TITLE
HandlerTest

### ISSUE THREAD

**Issue by MarshalT** [nnhy/NewLife.Net.Tests#5]
乱序的问题还是存在。
![image](https://user-images.githubusercontent.com/33778588/55049139-f30b7e80-5085-11e9-9a8a-782366cda7c7.png)

**Comment by nnhy** [comment]
这是正常的，因为你使用了SRMP协议编码器。

在以前的版本，Tcp收到数据包后先拆包为一个个消息，在IO线程然后逐个处理。
在ApiServer中，这种机制导致并发请求不得不排队处理，吞吐率难以提升。

在上个月升级了新的机制，Tcp拆包以后，通过线程池并行处理所有消息，IO线程不等待任何处理即可返回IOCP接收下一个数据包。新机制带来了吞吐率大增！

因此，基于消息处理的协议，有可能乱序！
（在UDP中全部都是消息包异步处理，也会乱序）

**Comment by MarshalT** [comment]
这样的啊，能避免乱序就更好了。

**Comment by nnhy** [comment]
新增的优化机制，除了产生乱序消息，还导致了其它衍生问题，我们再考虑优化
